# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Diagnosis\Model\Diagnosis:
    type: mappedSuperclass
    repositoryClass: Accard\Bundle\DiagnosisBundle\Doctrine\ORM\DiagnosisRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        startDate:
            type: datetime
            nullable: false
        endDate:
            type: datetime
            nullable: true

    manyToOne:
        parent:
            targetEntity: Accard\Component\Diagnosis\Model\DiagnosisInterface
            inversedBy: comorbidities
            joinColumn:
                name: parentId
                referencedColumnName: id
                nullable: true
        primary:
            targetEntity: Accard\Component\Diagnosis\Model\DiagnosisInterface
            inversedBy: recurrences
            joinColumn:
                name: primaryId
                referencedColumnName: id
                nullable: true

    oneToMany:
        comorbidities:
            targetEntity: Accard\Component\Diagnosis\Model\DiagnosisInterface
            mappedBy: parent
        recurrences:
            targetEntity: Accard\Component\Diagnosis\Model\DiagnosisInterface
            mappedBy: primary
        fields:
            targetEntity: Accard\Component\Diagnosis\Model\FieldValueInterface
            mappedBy: subject
            orphanRemoval: true
            cascade: ["all"]