imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @AccardCoreBundle/Resources/config/app/main.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: %kernel.root_dir%/config/routing.yml
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
        assets_version: %accard.core_version.id%
        assets_version_format: %%s?release=%%s
    default_locale:  %locale%
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: %accard_app_name%
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    form:
        resources:
            - 'AccardUIBundle::forms.html.twig'
            #- 'form_div_layout.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ AccardWebBundle ]
    filters:
        cssrewrite: ~

# Doctrine Migrations
doctrine_migrations:
    dir_name: %kernel.root_dir%/migrations/%database_driver%
    name: Accard Migrations
    namespace: Accard\Migrations

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            accard:
                driver:   %accard_database_driver%
                host:     %accard_database_host%
                port:     %accard_database_port%
                dbname:   %accard_database_name%
                user:     %accard_database_user%
                password: %accard_database_password%
                charset:  AL32UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    AccardActivityBundle: ~
                    AccardAttributeBundle: ~
                    AccardBehaviorBundle: ~
                    AccardCoreBundle: ~
                    AccardDiagnosisBundle: ~
                    AccardDrugBundle: ~
                    AccardFieldBundle: ~
                    AccardOptionBundle: ~
                    AccardPatientBundle: ~
                    AccardPhaseBundle: ~
                    AccardRegimenBundle: ~
                    AccardResourceBundle: ~
                    AccardSampleBundle: ~
                    AccardSettingsBundle: ~
                    AccardTemplateBundle: ~
                    AccardUIBundle: ~
                    AccardWebBundle: ~
                    LexikTranslationBundle: ~
                    loggable:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            accard:
                connection: accard
                mappings:
                    AccardPDSBundle: ~
#                    AccardVelosBundle: ~
            pds:
                connection: accard
                mappings:
                    AccardPDSBundle: ~
#            velos:
#                connection: accard
#                mappings:
#                    AccardVelosBundle: ~

# Wire in lexik translations GUI
lexik_translation:
    base_layout: AccardUIBundle:Backend:layout.html.twig

# Swiftmailer Configuration - DISABLED in 1.0
# swiftmailer:
#     transport: %mailer_transport%
#     host:      %mailer_host%
#     username:  %mailer_user%
#     password:  %mailer_password%
#     spool:     { type: memory }

accard_resource:
    import:
        signals: %accard_import_signals%
