security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPERUSER: ROLE_ADMIN

    providers:
        penn:
            id: dag.security.user_provider

    firewalls:
        login:
            pattern: ^/login$
            anonymous: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|assets)/
            security: false

        api:
            pattern: ^/api
            anonymous: ~

        main:
            pattern: ^/
            stateless: true
            simple_preauth:
                authenticator: dag.security.cosign_authenticator
                provider: penn
            anonymous: false
            switch_user:
                role: ROLE_SUPERUSER
                parameter: _switch

    access_control:
        - { path: ^/administration, roles: ROLE_SUPERUSER }
