# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Bundle\ImportBundle\Model\Import:
    type: mappedSuperclass
    table: meta_import
    repositoryClass: Accard\Bundle\ImportBundle\Doctrine\ORM\ImportRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        active:
            type: boolean
            nullable: false
        startTimestamp:
            type: decimal
            scale: 3
            precision: 13
            nullable: false
        endTimestamp:
            type: decimal
            scale: 3
            precision: 13
            nullable: false
        importer:
            type: string
            length: 36
            nullable: false
        criteria:
            type: array
            nullable: false

    oneToMany:
        records:
            targetEntity: Accard\Bundle\ImportBundle\Model\RecordInterface
            mappedBy: import
            orphanRemoval: true
            cascade: ["all"]