# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type.diagnosis.class: Accard\Bundle\DiagnosisBundle\Form\Type\DiagnosisType
    accard.builder.diagnosis.class: Accard\Component\Diagnosis\Builder\DiagnosisBuilder

services:

    accard.form.type.diagnosis:
        class: %accard.form.type.diagnosis.class%
        arguments:
            - %accard.model.diagnosis.class%
            - %accard.validation_group.diagnosis%
            - @accard.builder.diagnosis
            - @accard.option.provider
        tags:
            - { name: form.type, alias: accard_diagnosis }

    accard.builder.diagnosis:
        class: %accard.builder.diagnosis.class%
        arguments:
            - @accard.manager.diagnosis
            - @accard.repository.diagnosis
            - @accard.repository.diagnosis_field
            - @accard.repository.diagnosis_field_value