# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.type.diagnosis.class: Accard\Bundle\DiagnosisBundle\Form\Type\DiagnosisType

services:

    accard.form.type.diagnosis:
        class: %accard.form.type.diagnosis.class%
        arguments:
            - %accard.model.diagnosis.class%
            - %accard.validation_group.diagnosis%
            - @accard.option.provider
        tags:
            - { name: form.type, alias: accard_diagnosis }
