# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_backend_behavior_alcohol:
    resource: @AccardWebBundle/Resources/config/routing/backend/behavior/alcohol.yml
    prefix: /alcohol

accard_backend_behavior_smoking:
    resource: @AccardWebBundle/Resources/config/routing/backend/behavior/smoking.yml
    prefix: /smoking

accard_backend_behavior_illicit_drugs:
    resource: @AccardWebBundle/Resources/config/routing/backend/behavior/illicit_drug.yml
    prefix: /illicit_drugs

accard_backend_behavior_occupation:
    resource: @AccardWebBundle/Resources/config/routing/backend/behavior/occupation.yml
    prefix: /occupation

accard_backend_behavior_education:
    resource: @AccardWebBundle/Resources/config/routing/backend/behavior/education.yml
    prefix: /education