# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_backend_diagnosis_design:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.diagnosis:designAction
        _accard:
            template: AccardWebBundle:Backend/Diagnosis:design.html.twig

accard_backend_diagnosis_settings_update:
    pattern: /settings/update
    methods: [PUT, POST]
    defaults:
        _controller: accard.controller.settings:updateAction
        namespace: diagnosis
        redirect: accard_backend_diagnosis_design

accard_backend_diagnosis_field_create:
    pattern: /field/new
    methods: [GET, POST]
    defaults:
        _controller: accard.controller.diagnosis_field:createAction
        _accard:
            template: AccardWebBundle:Backend/Diagnosis:fieldCreate.html.twig
            redirect: accard_backend_diagnosis_design

accard_backend_diagonsis_field_update:
    pattern: /field/{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: accard.controller.diagnosis_field:updateAction
        _accard:
            template: AccardWebBundle:Backend/Diagnosis:fieldUpdate.html.twig
            redirect: accard_backend_diagnosis_design

accard_backend_diagnosis_field_delete:
    pattern: /field/{id}
    methods: [DELETE]
    defaults:
        _controller: accard.controller.diagnosis_field:deleteAction
        _accard:
            template: AccardWebBundle:Backend/Misc:delete.html.twig
            redirect: accard_backend_diagnosis_design