# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

accard_import_dashboard:
    pattern: /
    methods: [GET]
    defaults:
        _controller: accard.controller.import:dashboardAction
        _accard:
            template: AccardImportBundle::dashboard.html.twig

accard_import_importer_index:
    pattern: /importers
    methods: [GET]
    defaults:
        _controller: accard.controller.import:listImportersAction
        _accard:
            template: AccardImportBundle::listImporters.html.twig

accard_import_importer_show:
    pattern: /importer/{importer}
    methods: [GET]
    requirements: { importer: '[a-z_-]{3,36}' }
    defaults:
        _controller: accard.controller.import:showImporterAction
        _accard:
            template: AccardImportBundle::showImporter.html.twig

accard_import_importer_summary:
    pattern: /importer/{importer}/summary
    methods: [GET]
    requirements: { importer: '[a-z_-]{3,36}' }
    defaults:
        _controller: accard.controller.import:summarizeImporterAction
        _accard:
            template: AccardImportBundle::summarizeImporter.html.twig