# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.import.registry.class: Accard\Bundle\ImportBundle\Import\ImporterRegistry
    accard.import.builder_factory.class: Accard\Bundle\ImportBundle\Import\ImportBuilderFactory
    accard.import.manager.class: Accard\Bundle\ImportBundle\Import\ImportManager
    accard.import.analyzer.class: Accard\Bundle\ImportBundle\Import\ImporterAnalyzer
    accard.import.view_factory.class: Accard\Bundle\ImportBundle\Import\ImporterViewFactory
    accard.import.controller.class: Accard\Bundle\ImportBundle\Controller\ImportController

services:

#    accard.import.importer_registry:
#        class: %accard.import.registry.class%
#        arguments:
#            - @event_dispatcher#

#    accard.import.builder_factory:
#        class: %accard.import.builder_factory.class%
#        arguments:
#            - @accard.manager.import
#            - @accard.repository.import
#            - @accard.repository.record
#            - @event_dispatcher#

#    accard.import.manager:
#        class: %accard.import.manager.class%
#        arguments:
#            - @accard.manager.import
#            - @accard.import.importer_registry
#            - @event_dispatcher#

#    accard.import.view_factory:
#        class: %accard.import.view_factory.class%#

#    accard.import.analyzer:
#        class: %accard.import.analyzer.class%
#        arguments:
#            - @accard.import.importer_registry
#            - @accard.import.view_factory
