# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.templating.helper.import.class: Accard\Bundle\ImportBundle\Templating\Helper\ImportHelper

services:

#    accard.templating.helper.import:
#        class: %accard.templating.helper.import.class%
#        arguments: ['@accard.import.analyzer']
#        tags:
#            - { name: templating.helper, alias: accard_import }