# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.twig.extension.import.class: Accard\Bundle\ImportBundle\Twig\ImportExtension

services:

#    accard.twig.extension.import:
#        class: %accard.twig.extension.import.class%
#        arguments: ['@accard.templating.helper.import']
#        tags:
#            - { name: twig.extension }
