# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.extension.accard_attribute.class: Accard\Bundle\CoreBundle\Form\Extension\AttributeTypeExtension
    accard.form.extension.accard_diagnosis.class: Accard\Bundle\CoreBundle\Form\Extension\DiagnosisTypeExtension
    accard.form.extension.accard_behavior.class: Accard\Bundle\CoreBundle\Form\Extension\BehaviorTypeExtension
    accard.flow.scenario.basic_patient.class: Accard\Bundle\CoreBundle\Flow\Scenario\BasicPatientScenario
    accard.flow.step.create_patient.class: Accard\Bundle\CoreBundle\Flow\Step\CreatePatientStep
    accard.flow.step.create_diagnosis.class: Accard\Bundle\CoreBundle\Flow\Step\CreateDiagnosisStep
    accard.provider.import_patient.class: Accard\Bundle\CoreBundle\Provider\ImportPatientProvider

services:
    accard.form.extension.accard_attribute:
        class: %accard.form.extension.accard_attribute.class%
        arguments:
            - %accard.model.patient.class%
        tags:
            - { name: form.type_extension, alias: accard_attribute }

    accard.form.extension.accard_behavior:
        class: %accard.form.extension.accard_behavior.class%
        arguments:
            - %accard.model.patient.class%
        tags:
            - { name: form.type_extension, alias: accard_behavior }

    accard.form.extension.accard_diagnosis:
        class: %accard.form.extension.accard_diagnosis.class%
        arguments:
            - %accard.model.patient.class%
            - %accard.model.phase.class%
        tags:
            - { name: form.type_extension, alias: accard_diagnosis }

    accard.flow.scenario.basic_patient:
        class: %accard.flow.scenario.basic_patient.class%
        tags:
            - { name: accard.flow.scenario, alias: basic_patient }

    accard.flow.step.create_patient:
        class: %accard.flow.step.create_patient.class%
        arguments:
            - @accard.repository.patient
            - %accard.model.patient.class%
        tags:
            - { name: accard.flow.step, alias: create_patient }

    accard.flow.step.create_diagnosis:
        class: %accard.flow.step.create_diagnosis.class%
        arguments:
            - @accard.repository.diagnosis
            - %accard.model.diagnosis.class%
        tags:
            - { name: accard.flow.step, alias: create_diagnosis }

    accard.provider.import_patient:
        class: %accard.provider.import_patient.class%
        arguments:
            - @accard.repository.import_patient

