# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.form.extension.accard_diagnosis.class: Accard\Bundle\CoreBundle\Form\Extension\DiagnosisTypeExtension

services:

    accard.form.extension.accard_diagnosis:
        class: %accard.form.extension.accard_diagnosis.class%
        arguments:
            - %accard.model.patient.class%
            - %accard.model.phase.class%
        tags:
            - { name: form.type_extension, alias: accard_diagnosis }