# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:

    accard.settings_schema.general.class: Accard\Bundle\CoreBundle\Settings\GeneralSettingsSchema
    accard.settings_schema.theme.class: Accard\Bundle\CoreBundle\Settings\ThemeSettingsSchema
    accard.settings_schema.patient.class: Accard\Bundle\CoreBundle\Settings\PatientSettingsSchema

services:

    accard.settings_schema.general:
        class: %accard.settings_schema.general.class%
        tags:
            - { name: accard.settings_schema, namespace: general }

    accard.settings_schema.theme:
        class: %accard.settings_schema.theme.class%
        tags:
            - { name: accard.settings_schema, namespace: theme }

    accard.settings_schema.patient:
        class: %accard.settings_schema.patient.class%
        tags:
            - { name: accard.settings_schema, namespace: patient }