<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20141113160138 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'oracle', 'Migration can only be executed safely on \'oracle\'.');
        
        $this->addSql('CREATE SEQUENCE accard_setting_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_import_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_activity_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_attribute_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_behavior_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_diagnosis_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_diagnosis_phase_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_import_activity_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_import_patient_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_import_sample_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_patient_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_patient_phase_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_regimen_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_sample_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_sample_source_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_option_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_option_value_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_patient_field_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_patient_field_value_id_ START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_diagnosis_code_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_diagnosis_code_group_id START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_diagnosis_field_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_diagnosis_field_value_i START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_behavior_prototype_fiel START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_behavior_prototype_id_s START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_attribute_prototype_fie START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_attribute_prototype_id_ START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_sample_prototype_field_ START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_sample_prototype_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_regimen_prototype_field START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_regimen_prototype_id_se START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_activity_prototype_fiel START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE SEQUENCE accard_activity_prototype_id_s START WITH 1 MINVALUE 1 INCREMENT BY 1');
        $this->addSql('CREATE TABLE accard_setting (id NUMBER(10) NOT NULL, namespace VARCHAR2(120) NOT NULL, name VARCHAR2(120) NOT NULL, value CLOB DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN accard_setting.value IS \'(DC2Type:object)\'');
        $this->addSql('CREATE TABLE accard_import (id NUMBER(10) NOT NULL, active NUMBER(1) NOT NULL, startTimestamp NUMERIC(13, 3) NOT NULL, endTimestamp NUMERIC(13, 3) NOT NULL, importer VARCHAR2(36) NOT NULL, criteria CLOB NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN accard_import.criteria IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_activity (id NUMBER(10) NOT NULL, activityDate DATE NOT NULL, prototypeId NUMBER(10) NOT NULL, patientId NUMBER(10) NOT NULL, diagnosisId NUMBER(10) DEFAULT NULL NULL, regimenId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C69BB6459B116E9A ON accard_activity (prototypeId)');
        $this->addSql('CREATE INDEX IDX_C69BB6458F803478 ON accard_activity (patientId)');
        $this->addSql('CREATE INDEX IDX_C69BB645D0EA680C ON accard_activity (diagnosisId)');
        $this->addSql('CREATE INDEX IDX_C69BB64585CA7E31 ON accard_activity (regimenId)');
        $this->addSql('CREATE TABLE accard_attribute (id NUMBER(10) NOT NULL, prototypeId NUMBER(10) NOT NULL, patientId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_77180DB19B116E9A ON accard_attribute (prototypeId)');
        $this->addSql('CREATE INDEX IDX_77180DB18F803478 ON accard_attribute (patientId)');
        $this->addSql('CREATE TABLE accard_behavior (id NUMBER(10) NOT NULL, startDate TIMESTAMP(0) NOT NULL, endDate TIMESTAMP(0) DEFAULT NULL NULL, prototypeId NUMBER(10) NOT NULL, patientId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_51441FAF9B116E9A ON accard_behavior (prototypeId)');
        $this->addSql('CREATE INDEX IDX_51441FAF8F803478 ON accard_behavior (patientId)');
        $this->addSql('CREATE TABLE accard_diagnosis (id NUMBER(10) NOT NULL, startDate TIMESTAMP(0) NOT NULL, endDate TIMESTAMP(0) DEFAULT NULL NULL, codeId NUMBER(10) NOT NULL, parentId NUMBER(10) DEFAULT NULL NULL, primaryId NUMBER(10) DEFAULT NULL NULL, patientId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F3B3ED77B5FC0459 ON accard_diagnosis (codeId)');
        $this->addSql('CREATE INDEX IDX_F3B3ED7710EE4CEE ON accard_diagnosis (parentId)');
        $this->addSql('CREATE INDEX IDX_F3B3ED777BB601C ON accard_diagnosis (primaryId)');
        $this->addSql('CREATE INDEX IDX_F3B3ED778F803478 ON accard_diagnosis (patientId)');
        $this->addSql('CREATE TABLE accard_diagnosis_phase (id NUMBER(10) NOT NULL, label VARCHAR2(255) NOT NULL, presentation VARCHAR2(255) NOT NULL, orderNumber NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE accard_diagnosis_phase_inst (target_id NUMBER(10) NOT NULL, phase_id NUMBER(10) NOT NULL, startDate TIMESTAMP(0) NOT NULL, endDate TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(target_id, phase_id))');
        $this->addSql('CREATE INDEX IDX_F09D7DB9158E0B66 ON accard_diagnosis_phase_inst (target_id)');
        $this->addSql('CREATE INDEX IDX_F09D7DB999091188 ON accard_diagnosis_phase_inst (phase_id)');
        $this->addSql('CREATE TABLE accard_import_activity (id NUMBER(10) NOT NULL, activityDate DATE NOT NULL, descriptions CLOB NOT NULL, status NUMBER(10) NOT NULL, patientId NUMBER(10) NOT NULL, diagnosisId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_81CEBD4E8F803478 ON accard_import_activity (patientId)');
        $this->addSql('CREATE INDEX IDX_81CEBD4ED0EA680C ON accard_import_activity (diagnosisId)');
        $this->addSql('COMMENT ON COLUMN accard_import_activity.descriptions IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_import_patient (id NUMBER(10) NOT NULL, mrn VARCHAR2(36) DEFAULT NULL NULL, firstName VARCHAR2(36) NOT NULL, lastName VARCHAR2(36) NOT NULL, dateOfBirth TIMESTAMP(0) NOT NULL, dateOfDeath TIMESTAMP(0) DEFAULT NULL NULL, descriptions CLOB NOT NULL, status NUMBER(10) NOT NULL, genderId NUMBER(10) NOT NULL, raceId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2814E1484DD64A ON accard_import_patient (mrn)');
        $this->addSql('CREATE INDEX IDX_A2814E14827402C ON accard_import_patient (genderId)');
        $this->addSql('CREATE INDEX IDX_A2814E145F9153BF ON accard_import_patient (raceId)');
        $this->addSql('COMMENT ON COLUMN accard_import_patient.descriptions IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_import_sample (id NUMBER(10) NOT NULL, amount NUMBER(10) NOT NULL, descriptions CLOB NOT NULL, status NUMBER(10) NOT NULL, sourceId NUMBER(10) DEFAULT NULL NULL, patientId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_173786F4EE155AE0 ON accard_import_sample (sourceId)');
        $this->addSql('CREATE INDEX IDX_173786F48F803478 ON accard_import_sample (patientId)');
        $this->addSql('COMMENT ON COLUMN accard_import_sample.descriptions IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_patient (id NUMBER(10) NOT NULL, mrn VARCHAR2(36) DEFAULT NULL NULL, firstName VARCHAR2(36) NOT NULL, lastName VARCHAR2(36) NOT NULL, dateOfBirth TIMESTAMP(0) NOT NULL, dateOfDeath TIMESTAMP(0) DEFAULT NULL NULL, genderId NUMBER(10) NOT NULL, raceId NUMBER(10) DEFAULT NULL NULL, targetId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_45453AFA84DD64A ON accard_patient (mrn)');
        $this->addSql('CREATE INDEX IDX_45453AFA827402C ON accard_patient (genderId)');
        $this->addSql('CREATE INDEX IDX_45453AFA5F9153BF ON accard_patient (raceId)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_45453AFA39659675 ON accard_patient (targetId)');
        $this->addSql('CREATE TABLE accard_patient_phase (id NUMBER(10) NOT NULL, label VARCHAR2(255) NOT NULL, presentation VARCHAR2(255) NOT NULL, orderNumber NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE accard_patient_phase_inst (target_id NUMBER(10) NOT NULL, phase_id NUMBER(10) NOT NULL, startDate TIMESTAMP(0) NOT NULL, endDate TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(target_id, phase_id))');
        $this->addSql('CREATE INDEX IDX_450F421158E0B66 ON accard_patient_phase_inst (target_id)');
        $this->addSql('CREATE INDEX IDX_450F42199091188 ON accard_patient_phase_inst (phase_id)');
        $this->addSql('CREATE TABLE accard_regimen (id NUMBER(10) NOT NULL, startDate TIMESTAMP(0) NOT NULL, endDate TIMESTAMP(0) DEFAULT NULL NULL, prototypeId NUMBER(10) NOT NULL, patientId NUMBER(10) NOT NULL, diagnosisId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7E8EF59E9B116E9A ON accard_regimen (prototypeId)');
        $this->addSql('CREATE INDEX IDX_7E8EF59E8F803478 ON accard_regimen (patientId)');
        $this->addSql('CREATE INDEX IDX_7E8EF59ED0EA680C ON accard_regimen (diagnosisId)');
        $this->addSql('CREATE TABLE accard_sample (id NUMBER(10) NOT NULL, amount NUMBER(10) NOT NULL, sourceId NUMBER(10) DEFAULT NULL NULL, prototypeId NUMBER(10) NOT NULL, patientId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6B6E6FFAEE155AE0 ON accard_sample (sourceId)');
        $this->addSql('CREATE INDEX IDX_6B6E6FFA9B116E9A ON accard_sample (prototypeId)');
        $this->addSql('CREATE INDEX IDX_6B6E6FFA8F803478 ON accard_sample (patientId)');
        $this->addSql('CREATE TABLE accard_sample_source (id NUMBER(10) NOT NULL, sourceDate TIMESTAMP(0) NOT NULL, amount NUMBER(10) DEFAULT NULL NULL, parentSampleId NUMBER(10) DEFAULT NULL NULL, patientId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5530F9C68C7A1510 ON accard_sample_source (parentSampleId)');
        $this->addSql('CREATE INDEX IDX_5530F9C68F803478 ON accard_sample_source (patientId)');
        $this->addSql('CREATE TABLE accard_option (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE accard_option_value (id NUMBER(10) NOT NULL, value VARCHAR2(255) NOT NULL, locked NUMBER(1) NOT NULL, optionId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_96657CDDCE78B7CC ON accard_option_value (optionId)');
        $this->addSql('CREATE TABLE accard_patient_field (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, type VARCHAR2(36) NOT NULL, allowMultiple NUMBER(1) NOT NULL, configuration CLOB NOT NULL, optionId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_54CED4B85E237E06 ON accard_patient_field (name)');
        $this->addSql('CREATE INDEX IDX_54CED4B8CE78B7CC ON accard_patient_field (optionId)');
        $this->addSql('COMMENT ON COLUMN accard_patient_field.configuration IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_patient_field_value (id NUMBER(10) NOT NULL, stringValue VARCHAR2(255) DEFAULT NULL NULL, dateValue TIMESTAMP(0) DEFAULT NULL NULL, numberValue NUMBER(10) DEFAULT NULL NULL, optionValueId NUMBER(10) DEFAULT NULL NULL, patientId NUMBER(10) NOT NULL, fieldId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E084E37081F9A87C ON accard_patient_field_value (optionValueId)');
        $this->addSql('CREATE INDEX IDX_E084E3708F803478 ON accard_patient_field_value (patientId)');
        $this->addSql('CREATE INDEX IDX_E084E3705E697A44 ON accard_patient_field_value (fieldId)');
        $this->addSql('CREATE TABLE accard_patient_fld_opt_map (optionvalueinterface_id NUMBER(10) NOT NULL, optionId NUMBER(10) NOT NULL, PRIMARY KEY(optionId, optionvalueinterface_id))');
        $this->addSql('CREATE INDEX IDX_C6EC0E8BCE78B7CC ON accard_patient_fld_opt_map (optionId)');
        $this->addSql('CREATE INDEX IDX_C6EC0E8B2D7CB67F ON accard_patient_fld_opt_map (optionvalueinterface_id)');
        $this->addSql('CREATE TABLE accard_diagnosis_code (id NUMBER(10) NOT NULL, code VARCHAR2(255) NOT NULL, description VARCHAR2(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BD5E178E77153098 ON accard_diagnosis_code (code)');
        $this->addSql('CREATE TABLE accard_diagnosis_codes_groups (codeId NUMBER(10) NOT NULL, groupId NUMBER(10) NOT NULL, PRIMARY KEY(codeId, groupId))');
        $this->addSql('CREATE INDEX IDX_E9D4D81DB5FC0459 ON accard_diagnosis_codes_groups (codeId)');
        $this->addSql('CREATE INDEX IDX_E9D4D81DED8188B0 ON accard_diagnosis_codes_groups (groupId)');
        $this->addSql('CREATE TABLE accard_diagnosis_code_group (id NUMBER(10) NOT NULL, name VARCHAR2(255) NOT NULL, presentation VARCHAR2(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F7D683B15E237E06 ON accard_diagnosis_code_group (name)');
        $this->addSql('CREATE TABLE accard_diagnosis_field (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, type VARCHAR2(36) NOT NULL, allowMultiple NUMBER(1) NOT NULL, configuration CLOB NOT NULL, optionId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AFEBBB2E5E237E06 ON accard_diagnosis_field (name)');
        $this->addSql('CREATE INDEX IDX_AFEBBB2ECE78B7CC ON accard_diagnosis_field (optionId)');
        $this->addSql('COMMENT ON COLUMN accard_diagnosis_field.configuration IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_diagnosis_field_value (id NUMBER(10) NOT NULL, stringValue VARCHAR2(255) DEFAULT NULL NULL, dateValue TIMESTAMP(0) DEFAULT NULL NULL, numberValue NUMBER(10) DEFAULT NULL NULL, optionValueId NUMBER(10) DEFAULT NULL NULL, diagnosisId NUMBER(10) NOT NULL, fieldId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1EA4358F81F9A87C ON accard_diagnosis_field_value (optionValueId)');
        $this->addSql('CREATE INDEX IDX_1EA4358FD0EA680C ON accard_diagnosis_field_value (diagnosisId)');
        $this->addSql('CREATE INDEX IDX_1EA4358F5E697A44 ON accard_diagnosis_field_value (fieldId)');
        $this->addSql('CREATE TABLE accard_diagnosis_fld_opt_map (optionvalueinterface_id NUMBER(10) NOT NULL, optionId NUMBER(10) NOT NULL, PRIMARY KEY(optionId, optionvalueinterface_id))');
        $this->addSql('CREATE INDEX IDX_38CCD874CE78B7CC ON accard_diagnosis_fld_opt_map (optionId)');
        $this->addSql('CREATE INDEX IDX_38CCD8742D7CB67F ON accard_diagnosis_fld_opt_map (optionvalueinterface_id)');
        $this->addSql('CREATE TABLE accard_bhvr_proto_fld (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, type VARCHAR2(36) NOT NULL, allowMultiple NUMBER(1) NOT NULL, configuration CLOB NOT NULL, optionId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D2CFF6735E237E06 ON accard_bhvr_proto_fld (name)');
        $this->addSql('CREATE INDEX IDX_D2CFF673CE78B7CC ON accard_bhvr_proto_fld (optionId)');
        $this->addSql('COMMENT ON COLUMN accard_bhvr_proto_fld.configuration IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_bhvr_proto_fldval (id NUMBER(10) NOT NULL, stringValue VARCHAR2(255) DEFAULT NULL NULL, dateValue TIMESTAMP(0) DEFAULT NULL NULL, numberValue NUMBER(10) DEFAULT NULL NULL, optionValueId NUMBER(10) DEFAULT NULL NULL, behavior_prototypeId NUMBER(10) NOT NULL, fieldId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8855F5A481F9A87C ON accard_bhvr_proto_fldval (optionValueId)');
        $this->addSql('CREATE INDEX IDX_8855F5A4BDE390E1 ON accard_bhvr_proto_fldval (behavior_prototypeId)');
        $this->addSql('CREATE INDEX IDX_8855F5A45E697A44 ON accard_bhvr_proto_fldval (fieldId)');
        $this->addSql('CREATE TABLE accard_bhvr_proto_fld_opt_map (optionvalueinterface_id NUMBER(10) NOT NULL, optionId NUMBER(10) NOT NULL, PRIMARY KEY(optionId, optionvalueinterface_id))');
        $this->addSql('CREATE INDEX IDX_5AD23C54CE78B7CC ON accard_bhvr_proto_fld_opt_map (optionId)');
        $this->addSql('CREATE INDEX IDX_5AD23C542D7CB67F ON accard_bhvr_proto_fld_opt_map (optionvalueinterface_id)');
        $this->addSql('CREATE TABLE accard_behavior_prototype (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE accard_behavior_prototype_map (prototypeId NUMBER(10) NOT NULL, subjectId NUMBER(10) NOT NULL, PRIMARY KEY(prototypeId, subjectId))');
        $this->addSql('CREATE INDEX IDX_98CC21519B116E9A ON accard_behavior_prototype_map (prototypeId)');
        $this->addSql('CREATE INDEX IDX_98CC21513E0C34EB ON accard_behavior_prototype_map (subjectId)');
        $this->addSql('CREATE TABLE accard_attr_proto_fld (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, type VARCHAR2(36) NOT NULL, allowMultiple NUMBER(1) NOT NULL, configuration CLOB NOT NULL, optionId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6C2852165E237E06 ON accard_attr_proto_fld (name)');
        $this->addSql('CREATE INDEX IDX_6C285216CE78B7CC ON accard_attr_proto_fld (optionId)');
        $this->addSql('COMMENT ON COLUMN accard_attr_proto_fld.configuration IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_attr_proto_fldval (id NUMBER(10) NOT NULL, stringValue VARCHAR2(255) DEFAULT NULL NULL, dateValue TIMESTAMP(0) DEFAULT NULL NULL, numberValue NUMBER(10) DEFAULT NULL NULL, optionValueId NUMBER(10) DEFAULT NULL NULL, attribute_prototypeId NUMBER(10) NOT NULL, fieldId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_324CF2E781F9A87C ON accard_attr_proto_fldval (optionValueId)');
        $this->addSql('CREATE INDEX IDX_324CF2E7A6CD9D4A ON accard_attr_proto_fldval (attribute_prototypeId)');
        $this->addSql('CREATE INDEX IDX_324CF2E75E697A44 ON accard_attr_proto_fldval (fieldId)');
        $this->addSql('CREATE TABLE accard_attr_proto_fld_opt_map (optionvalueinterface_id NUMBER(10) NOT NULL, optionId NUMBER(10) NOT NULL, PRIMARY KEY(optionId, optionvalueinterface_id))');
        $this->addSql('CREATE INDEX IDX_D58BF8B9CE78B7CC ON accard_attr_proto_fld_opt_map (optionId)');
        $this->addSql('CREATE INDEX IDX_D58BF8B92D7CB67F ON accard_attr_proto_fld_opt_map (optionvalueinterface_id)');
        $this->addSql('CREATE TABLE accard_attribute_prototype (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE accard_attribute_prototype_map (prototypeId NUMBER(10) NOT NULL, subjectId NUMBER(10) NOT NULL, PRIMARY KEY(prototypeId, subjectId))');
        $this->addSql('CREATE INDEX IDX_B6E609359B116E9A ON accard_attribute_prototype_map (prototypeId)');
        $this->addSql('CREATE INDEX IDX_B6E609353E0C34EB ON accard_attribute_prototype_map (subjectId)');
        $this->addSql('CREATE TABLE accard_sample_proto_fld (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, type VARCHAR2(36) NOT NULL, allowMultiple NUMBER(1) NOT NULL, configuration CLOB NOT NULL, optionId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D7ABA2F35E237E06 ON accard_sample_proto_fld (name)');
        $this->addSql('CREATE INDEX IDX_D7ABA2F3CE78B7CC ON accard_sample_proto_fld (optionId)');
        $this->addSql('COMMENT ON COLUMN accard_sample_proto_fld.configuration IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_sample_proto_fldval (id NUMBER(10) NOT NULL, stringValue VARCHAR2(255) DEFAULT NULL NULL, dateValue TIMESTAMP(0) DEFAULT NULL NULL, numberValue NUMBER(10) DEFAULT NULL NULL, optionValueId NUMBER(10) DEFAULT NULL NULL, sample_prototypeId NUMBER(10) NOT NULL, fieldId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FD68D33081F9A87C ON accard_sample_proto_fldval (optionValueId)');
        $this->addSql('CREATE INDEX IDX_FD68D3308D6C621A ON accard_sample_proto_fldval (sample_prototypeId)');
        $this->addSql('CREATE INDEX IDX_FD68D3305E697A44 ON accard_sample_proto_fldval (fieldId)');
        $this->addSql('CREATE TABLE accard_sample_proto_fld_opt_ma (optionvalueinterface_id NUMBER(10) NOT NULL, optionId NUMBER(10) NOT NULL, PRIMARY KEY(optionId, optionvalueinterface_id))');
        $this->addSql('CREATE INDEX IDX_9CECBE04CE78B7CC ON accard_sample_proto_fld_opt_ma (optionId)');
        $this->addSql('CREATE INDEX IDX_9CECBE042D7CB67F ON accard_sample_proto_fld_opt_ma (optionvalueinterface_id)');
        $this->addSql('CREATE TABLE accard_sample_prototype (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE accard_sample_prototype_map (prototypeId NUMBER(10) NOT NULL, subjectId NUMBER(10) NOT NULL, PRIMARY KEY(prototypeId, subjectId))');
        $this->addSql('CREATE INDEX IDX_B953D8249B116E9A ON accard_sample_prototype_map (prototypeId)');
        $this->addSql('CREATE INDEX IDX_B953D8243E0C34EB ON accard_sample_prototype_map (subjectId)');
        $this->addSql('CREATE TABLE accard_regimen_proto_fld (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, type VARCHAR2(36) NOT NULL, allowMultiple NUMBER(1) NOT NULL, configuration CLOB NOT NULL, optionId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E62A58515E237E06 ON accard_regimen_proto_fld (name)');
        $this->addSql('CREATE INDEX IDX_E62A5851CE78B7CC ON accard_regimen_proto_fld (optionId)');
        $this->addSql('COMMENT ON COLUMN accard_regimen_proto_fld.configuration IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_regimen_proto_fldval (id NUMBER(10) NOT NULL, stringValue VARCHAR2(255) DEFAULT NULL NULL, dateValue TIMESTAMP(0) DEFAULT NULL NULL, numberValue NUMBER(10) DEFAULT NULL NULL, optionValueId NUMBER(10) DEFAULT NULL NULL, regimen_prototypeId NUMBER(10) NOT NULL, fieldId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5378E08E81F9A87C ON accard_regimen_proto_fldval (optionValueId)');
        $this->addSql('CREATE INDEX IDX_5378E08E9E2C754D ON accard_regimen_proto_fldval (regimen_prototypeId)');
        $this->addSql('CREATE INDEX IDX_5378E08E5E697A44 ON accard_regimen_proto_fldval (fieldId)');
        $this->addSql('CREATE TABLE accard_regimen_proto_fld_opt_m (optionvalueinterface_id NUMBER(10) NOT NULL, optionId NUMBER(10) NOT NULL, PRIMARY KEY(optionId, optionvalueinterface_id))');
        $this->addSql('CREATE INDEX IDX_CCCE7B63CE78B7CC ON accard_regimen_proto_fld_opt_m (optionId)');
        $this->addSql('CREATE INDEX IDX_CCCE7B632D7CB67F ON accard_regimen_proto_fld_opt_m (optionvalueinterface_id)');
        $this->addSql('CREATE TABLE accard_regimen_prototype (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE accard_regimen_prototype_map (prototypeId NUMBER(10) NOT NULL, subjectId NUMBER(10) NOT NULL, PRIMARY KEY(prototypeId, subjectId))');
        $this->addSql('CREATE INDEX IDX_9524569C9B116E9A ON accard_regimen_prototype_map (prototypeId)');
        $this->addSql('CREATE INDEX IDX_9524569C3E0C34EB ON accard_regimen_prototype_map (subjectId)');
        $this->addSql('CREATE TABLE accard_activity_proto_fld (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, type VARCHAR2(36) NOT NULL, allowMultiple NUMBER(1) NOT NULL, configuration CLOB NOT NULL, optionId NUMBER(10) DEFAULT NULL NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81052DA55E237E06 ON accard_activity_proto_fld (name)');
        $this->addSql('CREATE INDEX IDX_81052DA5CE78B7CC ON accard_activity_proto_fld (optionId)');
        $this->addSql('COMMENT ON COLUMN accard_activity_proto_fld.configuration IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE accard_activity_proto_fldval (id NUMBER(10) NOT NULL, stringValue VARCHAR2(255) DEFAULT NULL NULL, dateValue TIMESTAMP(0) DEFAULT NULL NULL, numberValue NUMBER(10) DEFAULT NULL NULL, optionValueId NUMBER(10) DEFAULT NULL NULL, activity_prototypeId NUMBER(10) NOT NULL, fieldId NUMBER(10) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_182C8B0F81F9A87C ON accard_activity_proto_fldval (optionValueId)');
        $this->addSql('CREATE INDEX IDX_182C8B0F959F0496 ON accard_activity_proto_fldval (activity_prototypeId)');
        $this->addSql('CREATE INDEX IDX_182C8B0F5E697A44 ON accard_activity_proto_fldval (fieldId)');
        $this->addSql('CREATE TABLE accard_activity_proto_fld_opt_ (optionvalueinterface_id NUMBER(10) NOT NULL, optionId NUMBER(10) NOT NULL, PRIMARY KEY(optionId, optionvalueinterface_id))');
        $this->addSql('CREATE INDEX IDX_359EDC71CE78B7CC ON accard_activity_proto_fld_opt_ (optionId)');
        $this->addSql('CREATE INDEX IDX_359EDC712D7CB67F ON accard_activity_proto_fld_opt_ (optionvalueinterface_id)');
        $this->addSql('CREATE TABLE accard_activity_prototype (id NUMBER(10) NOT NULL, name VARCHAR2(120) NOT NULL, presentation VARCHAR2(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE accard_activity_prototype_map (prototypeId NUMBER(10) NOT NULL, subjectId NUMBER(10) NOT NULL, PRIMARY KEY(prototypeId, subjectId))');
        $this->addSql('CREATE INDEX IDX_FD0B1419B116E9A ON accard_activity_prototype_map (prototypeId)');
        $this->addSql('CREATE INDEX IDX_FD0B1413E0C34EB ON accard_activity_prototype_map (subjectId)');
        $this->addSql('ALTER TABLE accard_activity ADD CONSTRAINT FK_C69BB6459B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_activity_prototype (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_activity ADD CONSTRAINT FK_C69BB6458F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_activity ADD CONSTRAINT FK_C69BB645D0EA680C FOREIGN KEY (diagnosisId) REFERENCES accard_diagnosis (id)');
        $this->addSql('ALTER TABLE accard_activity ADD CONSTRAINT FK_C69BB64585CA7E31 FOREIGN KEY (regimenId) REFERENCES accard_regimen (id)');
        $this->addSql('ALTER TABLE accard_attribute ADD CONSTRAINT FK_77180DB19B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_attribute_prototype (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_attribute ADD CONSTRAINT FK_77180DB18F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_behavior ADD CONSTRAINT FK_51441FAF9B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_behavior_prototype (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_behavior ADD CONSTRAINT FK_51441FAF8F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_diagnosis ADD CONSTRAINT FK_F3B3ED77B5FC0459 FOREIGN KEY (codeId) REFERENCES accard_diagnosis_code (id)');
        $this->addSql('ALTER TABLE accard_diagnosis ADD CONSTRAINT FK_F3B3ED7710EE4CEE FOREIGN KEY (parentId) REFERENCES accard_diagnosis (id)');
        $this->addSql('ALTER TABLE accard_diagnosis ADD CONSTRAINT FK_F3B3ED777BB601C FOREIGN KEY (primaryId) REFERENCES accard_diagnosis (id)');
        $this->addSql('ALTER TABLE accard_diagnosis ADD CONSTRAINT FK_F3B3ED778F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_diagnosis_phase_inst ADD CONSTRAINT FK_F09D7DB9158E0B66 FOREIGN KEY (target_id) REFERENCES accard_diagnosis (id)');
        $this->addSql('ALTER TABLE accard_diagnosis_phase_inst ADD CONSTRAINT FK_F09D7DB999091188 FOREIGN KEY (phase_id) REFERENCES accard_diagnosis_phase (id)');
        $this->addSql('ALTER TABLE accard_import_activity ADD CONSTRAINT FK_81CEBD4E8F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_import_activity ADD CONSTRAINT FK_81CEBD4ED0EA680C FOREIGN KEY (diagnosisId) REFERENCES accard_diagnosis (id)');
        $this->addSql('ALTER TABLE accard_import_patient ADD CONSTRAINT FK_A2814E14827402C FOREIGN KEY (genderId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_import_patient ADD CONSTRAINT FK_A2814E145F9153BF FOREIGN KEY (raceId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_import_sample ADD CONSTRAINT FK_173786F4EE155AE0 FOREIGN KEY (sourceId) REFERENCES accard_sample_source (id)');
        $this->addSql('ALTER TABLE accard_import_sample ADD CONSTRAINT FK_173786F48F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_patient ADD CONSTRAINT FK_45453AFA827402C FOREIGN KEY (genderId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_patient ADD CONSTRAINT FK_45453AFA5F9153BF FOREIGN KEY (raceId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_patient ADD CONSTRAINT FK_45453AFA39659675 FOREIGN KEY (targetId) REFERENCES accard_import_patient (id)');
        $this->addSql('ALTER TABLE accard_patient_phase_inst ADD CONSTRAINT FK_450F421158E0B66 FOREIGN KEY (target_id) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_patient_phase_inst ADD CONSTRAINT FK_450F42199091188 FOREIGN KEY (phase_id) REFERENCES accard_patient_phase (id)');
        $this->addSql('ALTER TABLE accard_regimen ADD CONSTRAINT FK_7E8EF59E9B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_regimen_prototype (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_regimen ADD CONSTRAINT FK_7E8EF59E8F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_regimen ADD CONSTRAINT FK_7E8EF59ED0EA680C FOREIGN KEY (diagnosisId) REFERENCES accard_diagnosis (id)');
        $this->addSql('ALTER TABLE accard_sample ADD CONSTRAINT FK_6B6E6FFAEE155AE0 FOREIGN KEY (sourceId) REFERENCES accard_sample_source (id)');
        $this->addSql('ALTER TABLE accard_sample ADD CONSTRAINT FK_6B6E6FFA9B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_sample_prototype (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_sample ADD CONSTRAINT FK_6B6E6FFA8F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_sample_source ADD CONSTRAINT FK_5530F9C68C7A1510 FOREIGN KEY (parentSampleId) REFERENCES accard_sample (id)');
        $this->addSql('ALTER TABLE accard_sample_source ADD CONSTRAINT FK_5530F9C68F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_option_value ADD CONSTRAINT FK_96657CDDCE78B7CC FOREIGN KEY (optionId) REFERENCES accard_option (id)');
        $this->addSql('ALTER TABLE accard_patient_field ADD CONSTRAINT FK_54CED4B8CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_option (id)');
        $this->addSql('ALTER TABLE accard_patient_field_value ADD CONSTRAINT FK_E084E37081F9A87C FOREIGN KEY (optionValueId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_patient_field_value ADD CONSTRAINT FK_E084E3708F803478 FOREIGN KEY (patientId) REFERENCES accard_patient (id)');
        $this->addSql('ALTER TABLE accard_patient_field_value ADD CONSTRAINT FK_E084E3705E697A44 FOREIGN KEY (fieldId) REFERENCES accard_patient_field (id)');
        $this->addSql('ALTER TABLE accard_patient_fld_opt_map ADD CONSTRAINT FK_C6EC0E8BCE78B7CC FOREIGN KEY (optionId) REFERENCES accard_patient_field_value (id)');
        $this->addSql('ALTER TABLE accard_patient_fld_opt_map ADD CONSTRAINT FK_C6EC0E8B2D7CB67F FOREIGN KEY (optionvalueinterface_id) REFERENCES accard_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_diagnosis_codes_groups ADD CONSTRAINT FK_E9D4D81DB5FC0459 FOREIGN KEY (codeId) REFERENCES accard_diagnosis_code (id)');
        $this->addSql('ALTER TABLE accard_diagnosis_codes_groups ADD CONSTRAINT FK_E9D4D81DED8188B0 FOREIGN KEY (groupId) REFERENCES accard_diagnosis_code_group (id)');
        $this->addSql('ALTER TABLE accard_diagnosis_field ADD CONSTRAINT FK_AFEBBB2ECE78B7CC FOREIGN KEY (optionId) REFERENCES accard_option (id)');
        $this->addSql('ALTER TABLE accard_diagnosis_field_value ADD CONSTRAINT FK_1EA4358F81F9A87C FOREIGN KEY (optionValueId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_diagnosis_field_value ADD CONSTRAINT FK_1EA4358FD0EA680C FOREIGN KEY (diagnosisId) REFERENCES accard_diagnosis (id)');
        $this->addSql('ALTER TABLE accard_diagnosis_field_value ADD CONSTRAINT FK_1EA4358F5E697A44 FOREIGN KEY (fieldId) REFERENCES accard_diagnosis_field (id)');
        $this->addSql('ALTER TABLE accard_diagnosis_fld_opt_map ADD CONSTRAINT FK_38CCD874CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_diagnosis_field_value (id)');
        $this->addSql('ALTER TABLE accard_diagnosis_fld_opt_map ADD CONSTRAINT FK_38CCD8742D7CB67F FOREIGN KEY (optionvalueinterface_id) REFERENCES accard_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fld ADD CONSTRAINT FK_D2CFF673CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_option (id)');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fldval ADD CONSTRAINT FK_8855F5A481F9A87C FOREIGN KEY (optionValueId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fldval ADD CONSTRAINT FK_8855F5A4BDE390E1 FOREIGN KEY (behavior_prototypeId) REFERENCES accard_behavior (id)');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fldval ADD CONSTRAINT FK_8855F5A45E697A44 FOREIGN KEY (fieldId) REFERENCES accard_bhvr_proto_fld (id)');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fld_opt_map ADD CONSTRAINT FK_5AD23C54CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_bhvr_proto_fldval (id)');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fld_opt_map ADD CONSTRAINT FK_5AD23C542D7CB67F FOREIGN KEY (optionvalueinterface_id) REFERENCES accard_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_behavior_prototype_map ADD CONSTRAINT FK_98CC21519B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_behavior_prototype (id)');
        $this->addSql('ALTER TABLE accard_behavior_prototype_map ADD CONSTRAINT FK_98CC21513E0C34EB FOREIGN KEY (subjectId) REFERENCES accard_bhvr_proto_fld (id)');
        $this->addSql('ALTER TABLE accard_attr_proto_fld ADD CONSTRAINT FK_6C285216CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_option (id)');
        $this->addSql('ALTER TABLE accard_attr_proto_fldval ADD CONSTRAINT FK_324CF2E781F9A87C FOREIGN KEY (optionValueId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_attr_proto_fldval ADD CONSTRAINT FK_324CF2E7A6CD9D4A FOREIGN KEY (attribute_prototypeId) REFERENCES accard_attribute (id)');
        $this->addSql('ALTER TABLE accard_attr_proto_fldval ADD CONSTRAINT FK_324CF2E75E697A44 FOREIGN KEY (fieldId) REFERENCES accard_attr_proto_fld (id)');
        $this->addSql('ALTER TABLE accard_attr_proto_fld_opt_map ADD CONSTRAINT FK_D58BF8B9CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_attr_proto_fldval (id)');
        $this->addSql('ALTER TABLE accard_attr_proto_fld_opt_map ADD CONSTRAINT FK_D58BF8B92D7CB67F FOREIGN KEY (optionvalueinterface_id) REFERENCES accard_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_attribute_prototype_map ADD CONSTRAINT FK_B6E609359B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_attribute_prototype (id)');
        $this->addSql('ALTER TABLE accard_attribute_prototype_map ADD CONSTRAINT FK_B6E609353E0C34EB FOREIGN KEY (subjectId) REFERENCES accard_attr_proto_fld (id)');
        $this->addSql('ALTER TABLE accard_sample_proto_fld ADD CONSTRAINT FK_D7ABA2F3CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_option (id)');
        $this->addSql('ALTER TABLE accard_sample_proto_fldval ADD CONSTRAINT FK_FD68D33081F9A87C FOREIGN KEY (optionValueId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_sample_proto_fldval ADD CONSTRAINT FK_FD68D3308D6C621A FOREIGN KEY (sample_prototypeId) REFERENCES accard_sample (id)');
        $this->addSql('ALTER TABLE accard_sample_proto_fldval ADD CONSTRAINT FK_FD68D3305E697A44 FOREIGN KEY (fieldId) REFERENCES accard_sample_proto_fld (id)');
        $this->addSql('ALTER TABLE accard_sample_proto_fld_opt_ma ADD CONSTRAINT FK_9CECBE04CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_sample_proto_fldval (id)');
        $this->addSql('ALTER TABLE accard_sample_proto_fld_opt_ma ADD CONSTRAINT FK_9CECBE042D7CB67F FOREIGN KEY (optionvalueinterface_id) REFERENCES accard_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_sample_prototype_map ADD CONSTRAINT FK_B953D8249B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_sample_prototype (id)');
        $this->addSql('ALTER TABLE accard_sample_prototype_map ADD CONSTRAINT FK_B953D8243E0C34EB FOREIGN KEY (subjectId) REFERENCES accard_sample_proto_fld (id)');
        $this->addSql('ALTER TABLE accard_regimen_proto_fld ADD CONSTRAINT FK_E62A5851CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_option (id)');
        $this->addSql('ALTER TABLE accard_regimen_proto_fldval ADD CONSTRAINT FK_5378E08E81F9A87C FOREIGN KEY (optionValueId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_regimen_proto_fldval ADD CONSTRAINT FK_5378E08E9E2C754D FOREIGN KEY (regimen_prototypeId) REFERENCES accard_regimen (id)');
        $this->addSql('ALTER TABLE accard_regimen_proto_fldval ADD CONSTRAINT FK_5378E08E5E697A44 FOREIGN KEY (fieldId) REFERENCES accard_regimen_proto_fld (id)');
        $this->addSql('ALTER TABLE accard_regimen_proto_fld_opt_m ADD CONSTRAINT FK_CCCE7B63CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_regimen_proto_fldval (id)');
        $this->addSql('ALTER TABLE accard_regimen_proto_fld_opt_m ADD CONSTRAINT FK_CCCE7B632D7CB67F FOREIGN KEY (optionvalueinterface_id) REFERENCES accard_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_regimen_prototype_map ADD CONSTRAINT FK_9524569C9B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_regimen_prototype (id)');
        $this->addSql('ALTER TABLE accard_regimen_prototype_map ADD CONSTRAINT FK_9524569C3E0C34EB FOREIGN KEY (subjectId) REFERENCES accard_regimen_proto_fld (id)');
        $this->addSql('ALTER TABLE accard_activity_proto_fld ADD CONSTRAINT FK_81052DA5CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_option (id)');
        $this->addSql('ALTER TABLE accard_activity_proto_fldval ADD CONSTRAINT FK_182C8B0F81F9A87C FOREIGN KEY (optionValueId) REFERENCES accard_option_value (id)');
        $this->addSql('ALTER TABLE accard_activity_proto_fldval ADD CONSTRAINT FK_182C8B0F959F0496 FOREIGN KEY (activity_prototypeId) REFERENCES accard_activity (id)');
        $this->addSql('ALTER TABLE accard_activity_proto_fldval ADD CONSTRAINT FK_182C8B0F5E697A44 FOREIGN KEY (fieldId) REFERENCES accard_activity_proto_fld (id)');
        $this->addSql('ALTER TABLE accard_activity_proto_fld_opt_ ADD CONSTRAINT FK_359EDC71CE78B7CC FOREIGN KEY (optionId) REFERENCES accard_activity_proto_fldval (id)');
        $this->addSql('ALTER TABLE accard_activity_proto_fld_opt_ ADD CONSTRAINT FK_359EDC712D7CB67F FOREIGN KEY (optionvalueinterface_id) REFERENCES accard_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accard_activity_prototype_map ADD CONSTRAINT FK_FD0B1419B116E9A FOREIGN KEY (prototypeId) REFERENCES accard_activity_prototype (id)');
        $this->addSql('ALTER TABLE accard_activity_prototype_map ADD CONSTRAINT FK_FD0B1413E0C34EB FOREIGN KEY (subjectId) REFERENCES accard_activity_proto_fld (id)');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'oracle', 'Migration can only be executed safely on \'oracle\'.');
        
        $this->addSql('ALTER TABLE accard_activity_proto_fldval DROP CONSTRAINT FK_182C8B0F959F0496');
        $this->addSql('ALTER TABLE accard_attr_proto_fldval DROP CONSTRAINT FK_324CF2E7A6CD9D4A');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fldval DROP CONSTRAINT FK_8855F5A4BDE390E1');
        $this->addSql('ALTER TABLE accard_activity DROP CONSTRAINT FK_C69BB645D0EA680C');
        $this->addSql('ALTER TABLE accard_diagnosis DROP CONSTRAINT FK_F3B3ED7710EE4CEE');
        $this->addSql('ALTER TABLE accard_diagnosis DROP CONSTRAINT FK_F3B3ED777BB601C');
        $this->addSql('ALTER TABLE accard_diagnosis_phase_inst DROP CONSTRAINT FK_F09D7DB9158E0B66');
        $this->addSql('ALTER TABLE accard_import_activity DROP CONSTRAINT FK_81CEBD4ED0EA680C');
        $this->addSql('ALTER TABLE accard_regimen DROP CONSTRAINT FK_7E8EF59ED0EA680C');
        $this->addSql('ALTER TABLE accard_diagnosis_field_value DROP CONSTRAINT FK_1EA4358FD0EA680C');
        $this->addSql('ALTER TABLE accard_diagnosis_phase_inst DROP CONSTRAINT FK_F09D7DB999091188');
        $this->addSql('ALTER TABLE accard_patient DROP CONSTRAINT FK_45453AFA39659675');
        $this->addSql('ALTER TABLE accard_activity DROP CONSTRAINT FK_C69BB6458F803478');
        $this->addSql('ALTER TABLE accard_attribute DROP CONSTRAINT FK_77180DB18F803478');
        $this->addSql('ALTER TABLE accard_behavior DROP CONSTRAINT FK_51441FAF8F803478');
        $this->addSql('ALTER TABLE accard_diagnosis DROP CONSTRAINT FK_F3B3ED778F803478');
        $this->addSql('ALTER TABLE accard_import_activity DROP CONSTRAINT FK_81CEBD4E8F803478');
        $this->addSql('ALTER TABLE accard_import_sample DROP CONSTRAINT FK_173786F48F803478');
        $this->addSql('ALTER TABLE accard_patient_phase_inst DROP CONSTRAINT FK_450F421158E0B66');
        $this->addSql('ALTER TABLE accard_regimen DROP CONSTRAINT FK_7E8EF59E8F803478');
        $this->addSql('ALTER TABLE accard_sample DROP CONSTRAINT FK_6B6E6FFA8F803478');
        $this->addSql('ALTER TABLE accard_sample_source DROP CONSTRAINT FK_5530F9C68F803478');
        $this->addSql('ALTER TABLE accard_patient_field_value DROP CONSTRAINT FK_E084E3708F803478');
        $this->addSql('ALTER TABLE accard_patient_phase_inst DROP CONSTRAINT FK_450F42199091188');
        $this->addSql('ALTER TABLE accard_activity DROP CONSTRAINT FK_C69BB64585CA7E31');
        $this->addSql('ALTER TABLE accard_regimen_proto_fldval DROP CONSTRAINT FK_5378E08E9E2C754D');
        $this->addSql('ALTER TABLE accard_sample_source DROP CONSTRAINT FK_5530F9C68C7A1510');
        $this->addSql('ALTER TABLE accard_sample_proto_fldval DROP CONSTRAINT FK_FD68D3308D6C621A');
        $this->addSql('ALTER TABLE accard_import_sample DROP CONSTRAINT FK_173786F4EE155AE0');
        $this->addSql('ALTER TABLE accard_sample DROP CONSTRAINT FK_6B6E6FFAEE155AE0');
        $this->addSql('ALTER TABLE accard_option_value DROP CONSTRAINT FK_96657CDDCE78B7CC');
        $this->addSql('ALTER TABLE accard_patient_field DROP CONSTRAINT FK_54CED4B8CE78B7CC');
        $this->addSql('ALTER TABLE accard_diagnosis_field DROP CONSTRAINT FK_AFEBBB2ECE78B7CC');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fld DROP CONSTRAINT FK_D2CFF673CE78B7CC');
        $this->addSql('ALTER TABLE accard_attr_proto_fld DROP CONSTRAINT FK_6C285216CE78B7CC');
        $this->addSql('ALTER TABLE accard_sample_proto_fld DROP CONSTRAINT FK_D7ABA2F3CE78B7CC');
        $this->addSql('ALTER TABLE accard_regimen_proto_fld DROP CONSTRAINT FK_E62A5851CE78B7CC');
        $this->addSql('ALTER TABLE accard_activity_proto_fld DROP CONSTRAINT FK_81052DA5CE78B7CC');
        $this->addSql('ALTER TABLE accard_import_patient DROP CONSTRAINT FK_A2814E14827402C');
        $this->addSql('ALTER TABLE accard_import_patient DROP CONSTRAINT FK_A2814E145F9153BF');
        $this->addSql('ALTER TABLE accard_patient DROP CONSTRAINT FK_45453AFA827402C');
        $this->addSql('ALTER TABLE accard_patient DROP CONSTRAINT FK_45453AFA5F9153BF');
        $this->addSql('ALTER TABLE accard_patient_field_value DROP CONSTRAINT FK_E084E37081F9A87C');
        $this->addSql('ALTER TABLE accard_patient_fld_opt_map DROP CONSTRAINT FK_C6EC0E8B2D7CB67F');
        $this->addSql('ALTER TABLE accard_diagnosis_field_value DROP CONSTRAINT FK_1EA4358F81F9A87C');
        $this->addSql('ALTER TABLE accard_diagnosis_fld_opt_map DROP CONSTRAINT FK_38CCD8742D7CB67F');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fldval DROP CONSTRAINT FK_8855F5A481F9A87C');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fld_opt_map DROP CONSTRAINT FK_5AD23C542D7CB67F');
        $this->addSql('ALTER TABLE accard_attr_proto_fldval DROP CONSTRAINT FK_324CF2E781F9A87C');
        $this->addSql('ALTER TABLE accard_attr_proto_fld_opt_map DROP CONSTRAINT FK_D58BF8B92D7CB67F');
        $this->addSql('ALTER TABLE accard_sample_proto_fldval DROP CONSTRAINT FK_FD68D33081F9A87C');
        $this->addSql('ALTER TABLE accard_sample_proto_fld_opt_ma DROP CONSTRAINT FK_9CECBE042D7CB67F');
        $this->addSql('ALTER TABLE accard_regimen_proto_fldval DROP CONSTRAINT FK_5378E08E81F9A87C');
        $this->addSql('ALTER TABLE accard_regimen_proto_fld_opt_m DROP CONSTRAINT FK_CCCE7B632D7CB67F');
        $this->addSql('ALTER TABLE accard_activity_proto_fldval DROP CONSTRAINT FK_182C8B0F81F9A87C');
        $this->addSql('ALTER TABLE accard_activity_proto_fld_opt_ DROP CONSTRAINT FK_359EDC712D7CB67F');
        $this->addSql('ALTER TABLE accard_patient_field_value DROP CONSTRAINT FK_E084E3705E697A44');
        $this->addSql('ALTER TABLE accard_patient_fld_opt_map DROP CONSTRAINT FK_C6EC0E8BCE78B7CC');
        $this->addSql('ALTER TABLE accard_diagnosis DROP CONSTRAINT FK_F3B3ED77B5FC0459');
        $this->addSql('ALTER TABLE accard_diagnosis_codes_groups DROP CONSTRAINT FK_E9D4D81DB5FC0459');
        $this->addSql('ALTER TABLE accard_diagnosis_codes_groups DROP CONSTRAINT FK_E9D4D81DED8188B0');
        $this->addSql('ALTER TABLE accard_diagnosis_field_value DROP CONSTRAINT FK_1EA4358F5E697A44');
        $this->addSql('ALTER TABLE accard_diagnosis_fld_opt_map DROP CONSTRAINT FK_38CCD874CE78B7CC');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fldval DROP CONSTRAINT FK_8855F5A45E697A44');
        $this->addSql('ALTER TABLE accard_behavior_prototype_map DROP CONSTRAINT FK_98CC21513E0C34EB');
        $this->addSql('ALTER TABLE accard_bhvr_proto_fld_opt_map DROP CONSTRAINT FK_5AD23C54CE78B7CC');
        $this->addSql('ALTER TABLE accard_behavior DROP CONSTRAINT FK_51441FAF9B116E9A');
        $this->addSql('ALTER TABLE accard_behavior_prototype_map DROP CONSTRAINT FK_98CC21519B116E9A');
        $this->addSql('ALTER TABLE accard_attr_proto_fldval DROP CONSTRAINT FK_324CF2E75E697A44');
        $this->addSql('ALTER TABLE accard_attribute_prototype_map DROP CONSTRAINT FK_B6E609353E0C34EB');
        $this->addSql('ALTER TABLE accard_attr_proto_fld_opt_map DROP CONSTRAINT FK_D58BF8B9CE78B7CC');
        $this->addSql('ALTER TABLE accard_attribute DROP CONSTRAINT FK_77180DB19B116E9A');
        $this->addSql('ALTER TABLE accard_attribute_prototype_map DROP CONSTRAINT FK_B6E609359B116E9A');
        $this->addSql('ALTER TABLE accard_sample_proto_fldval DROP CONSTRAINT FK_FD68D3305E697A44');
        $this->addSql('ALTER TABLE accard_sample_prototype_map DROP CONSTRAINT FK_B953D8243E0C34EB');
        $this->addSql('ALTER TABLE accard_sample_proto_fld_opt_ma DROP CONSTRAINT FK_9CECBE04CE78B7CC');
        $this->addSql('ALTER TABLE accard_sample DROP CONSTRAINT FK_6B6E6FFA9B116E9A');
        $this->addSql('ALTER TABLE accard_sample_prototype_map DROP CONSTRAINT FK_B953D8249B116E9A');
        $this->addSql('ALTER TABLE accard_regimen_proto_fldval DROP CONSTRAINT FK_5378E08E5E697A44');
        $this->addSql('ALTER TABLE accard_regimen_prototype_map DROP CONSTRAINT FK_9524569C3E0C34EB');
        $this->addSql('ALTER TABLE accard_regimen_proto_fld_opt_m DROP CONSTRAINT FK_CCCE7B63CE78B7CC');
        $this->addSql('ALTER TABLE accard_regimen DROP CONSTRAINT FK_7E8EF59E9B116E9A');
        $this->addSql('ALTER TABLE accard_regimen_prototype_map DROP CONSTRAINT FK_9524569C9B116E9A');
        $this->addSql('ALTER TABLE accard_activity_proto_fldval DROP CONSTRAINT FK_182C8B0F5E697A44');
        $this->addSql('ALTER TABLE accard_activity_prototype_map DROP CONSTRAINT FK_FD0B1413E0C34EB');
        $this->addSql('ALTER TABLE accard_activity_proto_fld_opt_ DROP CONSTRAINT FK_359EDC71CE78B7CC');
        $this->addSql('ALTER TABLE accard_activity DROP CONSTRAINT FK_C69BB6459B116E9A');
        $this->addSql('ALTER TABLE accard_activity_prototype_map DROP CONSTRAINT FK_FD0B1419B116E9A');
        $this->addSql('DROP SEQUENCE accard_setting_id_seq');
        $this->addSql('DROP SEQUENCE accard_import_id_seq');
        $this->addSql('DROP SEQUENCE accard_activity_id_seq');
        $this->addSql('DROP SEQUENCE accard_attribute_id_seq');
        $this->addSql('DROP SEQUENCE accard_behavior_id_seq');
        $this->addSql('DROP SEQUENCE accard_diagnosis_id_seq');
        $this->addSql('DROP SEQUENCE accard_diagnosis_phase_id_seq');
        $this->addSql('DROP SEQUENCE accard_import_activity_id_seq');
        $this->addSql('DROP SEQUENCE accard_import_patient_id_seq');
        $this->addSql('DROP SEQUENCE accard_import_sample_id_seq');
        $this->addSql('DROP SEQUENCE accard_patient_id_seq');
        $this->addSql('DROP SEQUENCE accard_patient_phase_id_seq');
        $this->addSql('DROP SEQUENCE accard_regimen_id_seq');
        $this->addSql('DROP SEQUENCE accard_sample_id_seq');
        $this->addSql('DROP SEQUENCE accard_sample_source_id_seq');
        $this->addSql('DROP SEQUENCE accard_option_id_seq');
        $this->addSql('DROP SEQUENCE accard_option_value_id_seq');
        $this->addSql('DROP SEQUENCE accard_patient_field_id_seq');
        $this->addSql('DROP SEQUENCE accard_patient_field_value_id_');
        $this->addSql('DROP SEQUENCE accard_diagnosis_code_id_seq');
        $this->addSql('DROP SEQUENCE accard_diagnosis_code_group_id');
        $this->addSql('DROP SEQUENCE accard_diagnosis_field_id_seq');
        $this->addSql('DROP SEQUENCE accard_diagnosis_field_value_i');
        $this->addSql('DROP SEQUENCE accard_behavior_prototype_fiel');
        $this->addSql('DROP SEQUENCE accard_behavior_prototype_id_s');
        $this->addSql('DROP SEQUENCE accard_attribute_prototype_fie');
        $this->addSql('DROP SEQUENCE accard_attribute_prototype_id_');
        $this->addSql('DROP SEQUENCE accard_sample_prototype_field_');
        $this->addSql('DROP SEQUENCE accard_sample_prototype_id_seq');
        $this->addSql('DROP SEQUENCE accard_regimen_prototype_field');
        $this->addSql('DROP SEQUENCE accard_regimen_prototype_id_se');
        $this->addSql('DROP SEQUENCE accard_activity_prototype_fiel');
        $this->addSql('DROP SEQUENCE accard_activity_prototype_id_s');
        $this->addSql('DROP TABLE accard_setting');
        $this->addSql('DROP TABLE accard_import');
        $this->addSql('DROP TABLE accard_activity');
        $this->addSql('DROP TABLE accard_attribute');
        $this->addSql('DROP TABLE accard_behavior');
        $this->addSql('DROP TABLE accard_diagnosis');
        $this->addSql('DROP TABLE accard_diagnosis_phase');
        $this->addSql('DROP TABLE accard_diagnosis_phase_inst');
        $this->addSql('DROP TABLE accard_import_activity');
        $this->addSql('DROP TABLE accard_import_patient');
        $this->addSql('DROP TABLE accard_import_sample');
        $this->addSql('DROP TABLE accard_patient');
        $this->addSql('DROP TABLE accard_patient_phase');
        $this->addSql('DROP TABLE accard_patient_phase_inst');
        $this->addSql('DROP TABLE accard_regimen');
        $this->addSql('DROP TABLE accard_sample');
        $this->addSql('DROP TABLE accard_sample_source');
        $this->addSql('DROP TABLE accard_option');
        $this->addSql('DROP TABLE accard_option_value');
        $this->addSql('DROP TABLE accard_patient_field');
        $this->addSql('DROP TABLE accard_patient_field_value');
        $this->addSql('DROP TABLE accard_patient_fld_opt_map');
        $this->addSql('DROP TABLE accard_diagnosis_code');
        $this->addSql('DROP TABLE accard_diagnosis_codes_groups');
        $this->addSql('DROP TABLE accard_diagnosis_code_group');
        $this->addSql('DROP TABLE accard_diagnosis_field');
        $this->addSql('DROP TABLE accard_diagnosis_field_value');
        $this->addSql('DROP TABLE accard_diagnosis_fld_opt_map');
        $this->addSql('DROP TABLE accard_bhvr_proto_fld');
        $this->addSql('DROP TABLE accard_bhvr_proto_fldval');
        $this->addSql('DROP TABLE accard_bhvr_proto_fld_opt_map');
        $this->addSql('DROP TABLE accard_behavior_prototype');
        $this->addSql('DROP TABLE accard_behavior_prototype_map');
        $this->addSql('DROP TABLE accard_attr_proto_fld');
        $this->addSql('DROP TABLE accard_attr_proto_fldval');
        $this->addSql('DROP TABLE accard_attr_proto_fld_opt_map');
        $this->addSql('DROP TABLE accard_attribute_prototype');
        $this->addSql('DROP TABLE accard_attribute_prototype_map');
        $this->addSql('DROP TABLE accard_sample_proto_fld');
        $this->addSql('DROP TABLE accard_sample_proto_fldval');
        $this->addSql('DROP TABLE accard_sample_proto_fld_opt_ma');
        $this->addSql('DROP TABLE accard_sample_prototype');
        $this->addSql('DROP TABLE accard_sample_prototype_map');
        $this->addSql('DROP TABLE accard_regimen_proto_fld');
        $this->addSql('DROP TABLE accard_regimen_proto_fldval');
        $this->addSql('DROP TABLE accard_regimen_proto_fld_opt_m');
        $this->addSql('DROP TABLE accard_regimen_prototype');
        $this->addSql('DROP TABLE accard_regimen_prototype_map');
        $this->addSql('DROP TABLE accard_activity_proto_fld');
        $this->addSql('DROP TABLE accard_activity_proto_fldval');
        $this->addSql('DROP TABLE accard_activity_proto_fld_opt_');
        $this->addSql('DROP TABLE accard_activity_prototype');
        $this->addSql('DROP TABLE accard_activity_prototype_map');
    }
}
