# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\CodeGroup:
    type: mappedSuperclass
    table: accard_diagnosis_code_group

    oneToMany:
        family_cancer:
            targetEntity: Accard\Component\Attributes\Model\FamilyCancerInterface
            mappedBy: codeGroups
            orphanRemoval: true
            cascade: ["persist", "remove"]
