# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

# Dylan Pierce <piercedy@upenn.edu>

Accard\Component\Core\Model\OccupationBehavior:
    type: mappedSuperclass
    table: accard_occupation_behavior

    manyToOne:
        patient:
            targetEntity: Accard\Component\Patient\Model\PatientInterface
            inversedBy: behaviors
            joinColumn:
                name: patientId
                referencedColumnName: id
                nullable: false