# This file is part of the Accard package.
#
# (c) University of Pennsylvania
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

Accard\Component\Core\Model\Patient:
    type: mappedSuperclass
    table: accard_patient
    repositoryClass: Accard\Bundle\PatientBundle\Doctrine\ORM\PatientRepository

    oneToOne:
        target:
            targetEntity: Accard\Component\Core\Model\ImportPatientInterface
            inversedBy: subject
            fetch: EXTRA_LAZY
            joinColumn:
                name: targetId

    oneToMany:
        diagnoses:
            targetEntity: Accard\Component\Diagnosis\Model\DiagnosisInterface
            mappedBy: patient
            orphanRemoval: true
            cascade: ["persist", "remove"]
#        activities:
#            targetEntity: Accard\Component\Activity\Model\ActivityInterface
#            mappedBy: patient
#            orphanRemoval: true
#            cascade: ["persist", "remove"]
        phases:
            targetEntity: Accard\Component\Core\Model\PatientPhaseInterface
            mappedBy: patient
            orphanRemoval: true
            cascade: ["persist", "remove"]